# Generated by Django 6.0.3 on 2026-03-21 13:29

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_farmerprofile_transporterprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farmer_card_image',
            field=cloudinary.models.CloudinaryField(default='dqfdsf', max_length=255, verbose_name='farmer_card'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='national_id_image',
            field=cloudinary.models.CloudinaryField(default='qdsfqdf', max_length=255, verbose_name='national_id'),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wilaya', models.CharField(max_length=100)),
                ('baladiya', models.CharField(max_length=100)),
                ('farm_size', models.FloatField(help_text='In hectares')),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
