# Generated by Django 6.0.3 on 2026-03-21 13:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_farmerprofile_farmer_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporterprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farmer_card_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='farmer_card'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='national_id_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='national_id'),
        ),
    ]
