# Generated by Django 6.0.3 on 2026-03-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_transporterprofile_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
