# Generated by Django 6.0.3 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterprofile',
            name='baladiya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transporterprofile',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
