# Generated by Django 6.0.3 on 2026-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_buyerprofile_is_validated_buyerprofile_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='region',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transporterprofile',
            name='region',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
