# Generated by Django 6.0.3 on 2026-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_farmerprofile_region_transporterprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
