# Generated by Django 6.0.3 on 2026-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_buyerprofile_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporterprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
