# Generated by Django 6.0.3 on 2026-04-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_buyerprofile_is_rejected_farmerprofile_is_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='transporterprofile',
            name='is_rejected',
        ),
    ]
