# Generated by Django 6.0.3 on 2026-03-27 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('wilaya', models.CharField(blank=True, help_text='Empty = national price', max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton'), ('box', 'Box'), ('bag', 'Bag')], default='kg', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['product_name', 'wilaya'], name='official_pr_product_ba49d5_idx'), models.Index(fields=['valid_from'], name='official_pr_valid_f_2c3fbc_idx')],
            },
        ),
    ]
