# Generated by Django 6.0.3 on 2026-04-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0002_remove_officialprice_official_pr_product_ba49d5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='officialprice',
            name='official_pr_product_f6727c_idx',
        ),
    ]
