# Generated by Django 6.0.3 on 2026-04-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0003_remove_officialprice_official_pr_product_f6727c_idx'),
        ('products', '0005_remove_product_title_alter_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialprice',
            name='product_name',
        ),
        migrations.AddField(
            model_name='officialprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_prices', to='products.ministryproduct'),
        ),
        migrations.AlterField(
            model_name='officialprice',
            name='region',
            field=models.CharField(blank=True, help_text="e.g. 'north', 'south'. Leave blank for national or specific wilaya.", max_length=50),
        ),
        migrations.AlterField(
            model_name='officialprice',
            name='wilaya',
            field=models.CharField(blank=True, help_text='Empty = national or region-wide price.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='officialprice',
            index=models.Index(fields=['product', 'wilaya', 'region'], name='official_pr_product_2e1381_idx'),
        ),
    ]
