# Generated by Django 6.0.3 on 2026-04-05 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0005_populate_official_price_fk'),
        ('products', '0005_remove_product_title_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialprice',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='official_prices', to='products.ministryproduct'),
            preserve_default=False,
        ),
    ]
