# Generated by Django 6.0.3 on 2026-05-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0006_make_product_fk_required'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='officialprice',
            new_name='official_pr_product_c8e1cd_idx',
            old_name='official_pr_product_2e1381_idx',
        ),
        migrations.AlterField(
            model_name='officialprice',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Geographic region (North, South, etc.). Leave blank for national price.', null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.region'),
        ),
    ]
