# Generated by Django 6.0.3 on 2026-05-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0007_rename_official_pr_product_2e1381_idx_official_pr_product_c8e1cd_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='officialprice',
            new_name='official_pr_product_2e1381_idx',
            old_name='official_pr_product_c8e1cd_idx',
        ),
        migrations.AlterField(
            model_name='officialprice',
            name='region',
            field=models.CharField(blank=True, help_text="e.g. 'north', 'south'. Leave blank for national or specific wilaya.", max_length=50),
        ),
    ]
