# Generated by Django 6.0.3 on 2026-05-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0008_rename_official_pr_product_c8e1cd_idx_official_pr_product_2e1381_idx_and_more'),
        ('official_prices', '0009_convert_empty_region_to_null'),
    ]

    operations = [
    ]
