# Generated by Django 6.0.3 on 2026-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0010_merge_20260519_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialprice',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton'), ('box', 'Box'), ('bag', 'Bag'), ('liter', 'Liter')], default='kg', max_length=20),
        ),
    ]
