# Generated by Django 6.0.3 on 2026-03-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_price_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='season',
            field=models.CharField(max_length=20),
        ),
    ]
