# Generated by Django 6.0.3 on 2026-03-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_productitem_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.productitem'),
        ),
    ]
