# Generated by Django 6.0.3 on 2026-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='alger', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_wilaya',
            field=models.CharField(default='alger', max_length=255),
        ),
    ]
