# Generated by Django 6.0.3 on 2026-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_address_order_delivery_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_wilaya',
            field=models.CharField(max_length=255),
        ),
    ]
