# Generated by Django 6.0.3 on 2026-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn')], max_length=20),
        ),
    ]
