# Generated by Django 6.0.3 on 2026-04-28 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_alter_farm_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(default=10, help_text='Minimum temperature in Celsius')),
                ('temp_max', models.FloatField(default=35, help_text='Maximum temperature in Celsius')),
                ('humidity_min', models.FloatField(default=30, help_text='Minimum humidity in %')),
                ('humidity_max', models.FloatField(default=80, help_text='Maximum humidity in %')),
                ('soil_min', models.IntegerField(default=30, help_text='Minimum soil moisture in %')),
                ('soil_max', models.IntegerField(default=70, help_text='Maximum soil moisture in %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_thresholds', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('dht11', 'DHT11 Temperature/Humidity'), ('soil', 'Soil Moisture Sensor'), ('combined', 'Combined Sensor')], default='combined', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='farms.farm')),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temperature_high', 'Temperature High'), ('temperature_low', 'Temperature Low'), ('humidity_high', 'Humidity High'), ('humidity_low', 'Humidity Low'), ('soil_dry', 'Soil Too Dry'), ('soil_wet', 'Soil Too Wet'), ('device_offline', 'Device Offline')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farms.farm')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity in %', null=True)),
                ('soil_moisture', models.IntegerField(blank=True, help_text='Soil moisture in %', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery level %', null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='WiFi signal strength', null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='iot_sensord_device__6b5b25_idx'), models.Index(fields=['recorded_at'], name='iot_sensord_recorde_f70083_idx')],
            },
        ),
    ]
