# Generated by Django 6.0.3 on 2026-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_iotdevice_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='mac_address',
            field=models.CharField(blank=True, help_text='ESP32 MAC address (XX:XX:XX:XX:XX:XX)', max_length=17, null=True),
        ),
    ]
