# Generated by Django 6.0.3 on 2026-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_iotdevice_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
    ]
