# Generated by Django 6.0.3 on 2026-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_iotdevice_is_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='battery_level',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='signal_strength',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='fire_detected',
            field=models.BooleanField(default=False, help_text='Is fire detected?'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='fire_percent',
            field=models.IntegerField(blank=True, help_text='Fire probability %', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='fire_raw',
            field=models.IntegerField(blank=True, help_text='Raw flame sensor value (0-4095)', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='rain_detected',
            field=models.BooleanField(default=False, help_text='Is rain detected?'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='rain_percent',
            field=models.IntegerField(blank=True, help_text='Rain intensity %', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='rain_raw',
            field=models.IntegerField(blank=True, help_text='Raw rain sensor value (0-4095)', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('temperature_high', 'Temperature High'), ('temperature_low', 'Temperature Low'), ('humidity_high', 'Humidity High'), ('humidity_low', 'Humidity Low'), ('soil_dry', 'Soil Too Dry'), ('soil_wet', 'Soil Too Wet'), ('device_offline', 'Device Offline'), ('fire_detected', '🔥 Fire Detected'), ('rain_detected', '🌧️ Rain Detected'), ('heavy_rain', '⛈️ Heavy Rain Warning')], max_length=50),
        ),
    ]
